name: ci

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: shiftcraft
          POSTGRES_USER: shift
          POSTGRES_PASSWORD: shift
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U shift"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven
          
      - name: Build
        run: mvn -q -f backend/pom.xml -DskipTests=false verify
        env:
          DB_URL: jdbc:postgresql://localhost:5432/shiftcraft
          DB_USER: shift
          DB_PASS: shift